<?php require_once 'config/libs.inc'?>
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
	<meta http-equiv="content-type" content="text/html" />
	<meta name="author" content="Clement Mukendi" />
	<link href="style/css/bootstrap.css" rel="stylesheet" type="text/css" />
	<link href="style/css/style.css" rel="stylesheet" type="text/css" />
	<title>Currency - Converter</title>
</head>






